### ISSUE TITLE
cmeu crash on startup 

### ISSUE THREAD

**Issue by polemorin** [RedDuckss/CemUI#87] opened 2018-01-12 12:23 UTC
i followed a guide on how to run the emulator on pc
when i pressed play a new window opened (it has the words CEMU on it)
and after a few seconds i get the windows message "Wii U emulator is not responding"
and i have to close the programme .

please hep and thank you

**Comment by RedDuckss** [comment] 2018-01-12 15:48
Open the emulator without CemUI, then click `File` then `Load` and select the rom, and see if it still crashes. If it does then it is an issue with Cemu, not CemUI. If it does not crash then please edit your issue report to follow the correct format so that I can gather as much info as possible to help diagnose your issue.

**Comment by polemorin** [comment] 2018-01-12 15:51
it still crushes.
same error message and all.

**Comment by RedDuckss** [comment] 2018-01-12 15:56
Then it's a bad dump of the rom, your PC specs can't handle Cemu, or an issue with Cemu itself.

I assume you followed this tutorial http://themindhero.com/smmg.html ? If so, this tutorial contains outdated files. You should download the latest version of Cemu from the official source http://cemu.info/

I would also suggest re-dumping your game to see if there was an issue there.

What are your PC specs? You might not even be able to run it at all.

If the issue still persists then it's an issue with Cemu itself and isn't something I can fix. I didn't develop Cemu, I just made a frontend for it.

**Comment by RedDuckss** [comment] 2018-01-13 04:39
Seeing as the error reported is being thrown by Cemu and not CemUI, and the cause of the error has yet to be proven to be caused by CemUI, I will be closing this issue as it is an issue I cannot control.

**Closed by RedDuckss** 2018-01-13 04:39 UTC
