### ISSUE TITLE
Moving Application

### ISSUE THREAD

**Issue by davidevan84** [RedDuckss/CemUI#17] opened 2017-04-13 17:01 UTC
After you scroll through games, application window locks in place. Must move to the very top of game list for you to be able to move Application again.

**Comment by RedDuckss** [comment] 2017-04-13 17:07
Would you mind rewriting this issue report in the correct format :P

![format](http://i.imgur.com/oKj9EFI.png)

**Comment by MrIlliteracy** [comment] 2017-04-13 18:48
@davidevan84 I've been trying to recreate the bug with the little information you gave, I can only get it to happen sometimes. Also, how many games do you have? Exact steps for reproduction would be very much appreciated. Thank you 😄

**Comment by davidevan84** [comment] 2017-04-14 23:59
Sorry for the late response. Its pretty straight forward. If you are scrolled all the way to the top of the Application it works fine. If you scroll down at all it locks the application into place. For me its 100%. If its at the top meaning the first 3 games show up then it doesnt lock. If you scroll down even a little bit it now will not move at all.

**Comment by davidevan84** [comment] 2017-04-15 00:01
oh and 25 games show up in the list.

**Comment by RedDuckss** [comment] 2017-04-28 18:07
I know this is an old report, but I have finally gotten the program to experience this bug reliably (was unable to replicate the issue until now). Will work on a fix.

**Comment by MrIlliteracy** [comment] 2017-04-28 23:52
Oh, I forgot about this :p Sorry @davidevan84 I've been focusing on projects other than CemUI lately, but I'll be hopping back into development soon! (RedDucks take the wheel!)

**Comment by MrIlliteracy** [comment] 2017-05-12 22:11
Could be due to some part of the navbar (specifically the draggable part) scrolling with the game list.

**Comment by RedDuckss** [comment] 2017-08-28 22:34
Closing this issue since the source code in the master branch as well as the current latest release (`1.1.0`) is no longer maintained or supported. CemUI is being rewritten from the ground up in the 2.0 branch (currently does not have a functional UI) and will be merged to the master branch when ready.

**Closed by RedDuckss** 2017-08-28 22:34 UTC
Labels: bug
