### ISSUE TITLE
Stuck at the "Downloading Game Data" screen

### ISSUE THREAD

**Issue by 00BLOOD** [RedDuckss/CemUI#56] opened 2017-09-13 22:27 UTC
It takes forever to download it. I did the reinstallation but had no success.

I'm not sure on how to reproduce this bug. 
What I do know, is that, on the first time I installed CEMUI, it worked like a charm, but since I got more games, it stopped work properly, failing on loading ALL the existent  UI elements in the window. All i was geting is a clean background.

Then, i did the reinstallation (at least i think i did right), and now i am stuck at "Downloading Game Data" screen.

This is the directory (named "GAMES") that i specified for CEMUI read my games:
>https://i.imgur.com/BlB2yj6.png

**Comment by RedDuckss** [comment] 2017-09-13 22:34
What version of CemUI are you using (latest build, latest source code/dev version, etc), what games we’re working before this happened, what games did you add that made this bug occur, and how many games do you have

**Comment by 00BLOOD** [comment] 2017-09-13 22:45
`What version of CemUI are you using (latest build, latest source code/dev version, etc)`
I don't know the version. I guess 2.0.0 Alpha 1? Sorry for that =/ 
I did the download here (maybe that helps finding out): 
https://github.com/RedDuckss/CemUI/releases

`what games we’re working before this happened`
I had Yoshi's Woolly World and Breath of the Wild before all of this.

`what games did you add that made this bug occur`
-Captain Toad Treasure Tracker
-The Wind Waker HD
-Xenoblade Chronicles X

`how many games do you have`
5
-Breath of the Wild
-Yoshi's Woolly World
-Captain Toad Treasure Tracker
-The Wind Waker HD
-Xenoblade Chronicles X

**Comment by RedDuckss** [comment] 2017-09-13 22:57
This sounds like a known issue in the latest build. It should be fixed in the latest dev version, try that and report back if it still happens

**Comment by RedDuckss** [comment] 2017-09-14 16:53
I see that you reacted to my comment with a thumbs up. Does this indicate the issue is solved now? @00BLOOD

**Comment by Drakonas** [comment] 2017-09-15 00:17
I got the same issue, but hitting the close button and waiting until the command prompt ends processing the executable and retyping electron . gets it to load the games.

**Comment by RedDuckss** [comment] 2017-09-15 01:08
The root cause of this issue seems to be the custom API . I made the API custom, however assets like images are outsourced (the API responds with a list of 3rd party URLs for the images), and this seems to be causing issues. Many people seem to have trouble connecting to those URLs and many times they will hang and stop responding. I am considering downloading every image locally and serving them from the API itself though disk space is an issue here (there are 3,114 games stored in the API's database, many of which have up to a dozen attached assets, and nearly every image is HD which adds to the size)

**Comment by RedDuckss** [comment] 2017-09-24 18:26
Closing as the root cause of this has been fixed, all content is now served from the API and not outsourced.

**Closed by RedDuckss** 2017-09-24 18:26 UTC
