### ISSUE TITLE
CEMUI not loading any data from games, even when pointed to the correct directory

### ISSUE THREAD

**Issue by jazir5** [RedDuckss/CemUI#85] opened 2017-12-30 23:42 UTC
Newest version under releases at time of this posting

- I try loading a directory by adding the path and CEMUI does not update with an icon or anything related to the game.

- Add a directory

- CEMUI remains blank as if nothing were in the folder chosen

**Comment by RedDuckss** [comment] 2017-12-30 23:45
What is the structure of the game folder being selected

**Comment by jazir5** [comment] 2017-12-30 23:48
![game root directory](https://user-images.githubusercontent.com/31750063/34458043-ec53f372-ed78-11e7-95ca-af443716c376.png)
![Uploading smash directory.png…]()
![Uploading smash directory 2.png…]()

**Comment by jazir5** [comment] 2017-12-30 23:50
https://imgur.com/a/98NC8

root directory

**Comment by jazir5** [comment] 2017-12-30 23:51
Tried adding both of these for smash specifically

https://imgur.com/a/v6U54

**Comment by RedDuckss** [comment] 2018-01-13 04:47
Sorry for the late response. I didn't see that you responded.

After checking that album I now see your issue is the same one as #45 (please check the previous issue reports before filing a new one, this same issue has been reported several times and I simply link to #45)

This is working as intended and I will be closing this issue now.

**Closed by RedDuckss** 2018-01-13 04:47 UTC
