### ISSUE TITLE
Javascript error when downloading large games,or multiple games at once

### ISSUE THREAD

**Issue by headlesshorseman22** [RedDuckss/CemUI#94] opened 2018-01-24 23:24 UTC
![image](https://user-images.githubusercontent.com/35785061/35362460-44478ee0-011a-11e8-832f-e4b6294c6304.png)
![image](https://user-images.githubusercontent.com/35785061/35362469-50ecbd28-011a-11e8-8119-5b800f1d15e4.png)
title.

**Comment by RedDuckss** [comment] 2018-01-25 19:28
The first screenshot is an error caused by a timeout to Nintendo's eShop servers. Make sure you have a stable internet connection, and try to not download multiple games at once.

Second screenshot is a duplicate of #91. In which case I am closing this issue. Any further information should be posted on that issue report, please make sure your issue is not already reported before making a new report.

**Closed by RedDuckss** 2018-01-25 19:28 UTC
