### ISSUE TITLE
Stuck at this won't take long screen with version 2.1.1

### ISSUE THREAD

**Issue by MacXxs** [RedDuckss/CemUI#59] opened 2017-09-21 09:47 UTC
So, ya the title is self explenatory. I just installed the latest version, selected my cemu.exe version 1.9.1 and my games folder and I'm stuck at this screen.

**Comment by mrjvs** [comment] 2017-09-21 09:51
Please give more information. try to press "p" and show us the errors.

**Comment by MacXxs** [comment] 2017-09-21 09:57
Thank you for your quick response, this is the only error I could find.
https://gyazo.com/fba001bfc9774c677cf71b2c4d3f9f53

**Comment by mrjvs** [comment] 2017-09-21 10:02
Hmm, that is weird. Please try the latest source version. Source is always newest version possible. Installation instructions are in the readme: https://github.com/RedDuckss/CemUI/blob/master/README.md

**Comment by MacXxs** [comment] 2017-09-21 10:04
Okey, thank you, I'll give it a try

**Comment by MacXxs** [comment] 2017-09-21 10:16
I did what you tell me and i get this error: https://gyazo.com/521e580b5a8fca5d7ef6fd65c390594f

**Comment by mrjvs** [comment] 2017-09-21 10:50
Weird, I have notified redducks (the backend dev) of this.

**Comment by MacXxs** [comment] 2017-09-21 10:54
Thank you

**Comment by RedDuckss** [comment] 2017-09-21 14:54
I think I’ve found the cause for the error being thrown but as for the cause of the _error_ I’m a bit stumped. Based on the line number, the error occurs while getting the `Suggested` section. The endpoint seems to have returned HTML instead of JSON, and CemUI wasn’t designed to handle that. It assumes all responses are JSON, and treats them as such, and I accidentally put the error checking _after_ the JSON parsing.

But as to _why_ it returned HTML, I have no idea, since the endpoint itself is designed to only respond with JSON.

**Comment by RedDuckss** [comment] 2017-09-21 16:46
@MacXxs Please try the latest dev version, as I have pushed out an update that moves the error checking to before the JSON parsing (like it should have been originally) and also added some logging to log what the API actually returns. Please run the dev version and screenshot the command prompt log, and send it here as a reply.

**Comment by MacXxs** [comment] 2017-09-21 17:06
Okey, thank you for your response!!! At the moment i set foot at home i'll try it.

**Comment by MacXxs** [comment] 2017-09-22 13:26
Sorry for the delay, I was working. I've redownloaded the latest dev version and now I get this error: https://gyazo.com/b4b84bddce8cc3973034ac3c149ceb5c
Thanks for your attention!

**Comment by RedDuckss** [comment] 2017-09-22 13:35
@MacXxs My apologies, I added the logging to the wrong line. I just pushed a tiny update that just moves the logging to the correct line. Try now? You should still get an error, but it should be properly logged in the command prompt now.

**Comment by MacXxs** [comment] 2017-09-22 13:36
Okey no problem!!

**Comment by MacXxs** [comment] 2017-09-22 13:39
This is what i get: https://gyazo.com/f36c3deb16a777ad18afb0561ff7e644

**Comment by RedDuckss** [comment] 2017-09-22 13:42
Ahh okay. Now I see. This was cause by an oversight of mine. That API endpoint expects a list of genres, and I did not account for cases where no genres are give.

What games do you currently have? Even with a single game, it should still be pulling genres from it. The only time I can see where there would be no genres is if there are no games.

**Comment by MacXxs** [comment] 2017-09-22 13:48
The Legend of Zelda - Breath of The WIld

**Comment by RedDuckss** [comment] 2017-09-22 13:50
Folder structure? Could be in the wrong structure and CemUI is ignoring it because of that, causing there to be no valid games stored.

You can find an example of the proper folder structure here https://github.com/RedDuckss/CemUI/issues/45

**Comment by RedDuckss** [comment] 2017-09-22 14:02
Yupp, your issue is the exact same issue as #45. I posted a fix for it in that thread.

**Comment by MacXxs** [comment] 2017-09-22 14:04
Okey, thank you!

**Comment by RedDuckss** [comment] 2017-09-23 00:36
Assuming fixed and closing

**Closed by RedDuckss** 2017-09-23 00:36 UTC
